const partners = [
  { src: "assets/images/partners/discover.webp", alt: "discover" },
  { src: "assets/images/partners/ford.webp", alt: "ford" },
  { src: "assets/images/partners/sony.webp", alt: "sony" },
  { src: "assets/images/partners/lexmark.webp", alt: "lexmark" },
  { src: "assets/images/partners/blackveatech.webp", alt: "blackveatech" },
  { src: "assets/images/partners/manitowoc.webp", alt: "manitowoc" },
  { src: "assets/images/partners/fedex.webp", alt: "FedEx" },
  { src: "assets/images/partners/generalmotors.webp", alt: "General Motors" },
  { src: "assets/images/partners/exelon.webp", alt: "exelon" },
  { src: "assets/images/partners/amgen.webp", alt: "amgen" },
  { src: "assets/images/partners/calx.webp", alt: "calx" },
  { src: "assets/images/partners/bobazona.webp", alt: "bobazona" },
  { src: "assets/images/partners/cummins.webp", alt: "cummins" },
  { src: "assets/images/partners/navitas.webp", alt: "navitas" },
  { src: "assets/images/partners/royalepuppies.webp", alt: "Royale Puppies" },
  { src: "assets/images/partners/opticalpro.webp", alt: "Optical Pro" },
  { src: "assets/images/partners/snpglobal.webp", alt: "S&P Global" },
  { src: "assets/images/partners/unitednations.webp", alt: "united nations" },
  { src: "assets/images/partners/deutschebank.webp", alt: "deutsche bank" },
  { src: "assets/images/partners/whirlpool.webp", alt: "whirlpool" },
  { src: "assets/images/partners/yankeegroup.webp", alt: "yankee group" },
  { src: "assets/images/partners/nielsen.webp", alt: "nielsen" },
  { src: "assets/images/partners/mylan.webp", alt: "mylan" },
  {
    src: "assets/images/partners/ultimategaragedoors.webp",
    alt: "ultimate garage doors",
  },
  { src: "assets/images/partners/pfizer.webp", alt: "pfizer" },
  { src: "assets/images/partners/bmw.webp", alt: "bmw" },
  { src: "assets/images/partners/netflix.webp", alt: "netflix" },
];

export default partners;
